### ISSUE TITLE
Function suggestion - get schema files from actual data

### ISSUE THREAD

**Issue by odscjames** [open-contracting/ocdskit#181]
I have a piece of data - a release package.

I need the schema that that data follows (ie correct OCDS version and with extensions applied), both the package and the release bit.

Is there a function in OCDSKit, or elsewhere, that does this?

(I couldn't see it - sorry if missed! Also COVE will do this work, but I haven't yet looked to see if it's in a form I can easily dig out.)

Thanks,

**Comment by jpmckinney** [comment]
You can do it with https://ocdsextensionregistry.readthedocs.io/en/latest/api/profile_builder.html

You'd just need to pass it the package's `extensions` array.

As for the OCDS version, I'm not sure if you want the latest patch, etc. In any case, for most use cases, it doesn't make much sense to use 1.0.x, since 1.1.x is backwards-compatible and generally more correct.

**Comment by jpmckinney** [comment]
OCDS Kit does something similar here:

https://github.com/open-contracting/ocdskit/blob/dd10411c7f7bc0f81e808043d17d6bf800f3bb8e/ocdskit/combine.py#L162-L171

**Comment by jpmckinney** [comment]
1.0.3 adds a get_ocds_patch_tag function, to simplify the above a bit:

https://github.com/open-contracting/ocdskit/blob/81238891944e9bd53d692b5841d51da48788cb6e/ocdskit/combine.py#L162-L168

In your case it'd probably look like:

```python
from ocdskit.util import get_ocds_patch_tag
from ocdsextensionregistry import ProfileBuilder

tag = get_ocds_patch_tag(package.get("version", "1.0"))
builder = ProfileBuilder(tag, package.get("extensions", []))) 
schema = builder.patched_release_schema() 
```

**Comment by odscjames** [comment]
Thank you @jpmckinney
