### ISSUE TITLE
indent: Unexpectedly removes content

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocdskit#182]
I happened upon some unexpected behaviour when I tried to indent a file that contained non-unique keys under `/definitions/Award`.

To reproduce:

```bash
curl -LOJ https://gist.github.com/duncandewhurst/848ac5dc8bd101ead02badd188898281/raw/f4b6f5e0760ddd8a8efb0ee18d3aa5561d61fc02/release-schema.json
ocdskit indent release-schema.json
```

Result: one of the `properties` keys under `/definitions/Award` is removed.

**Comment by jpmckinney** [comment]
Hmm, any software that reads and writes JSON is very likely to remove duplicate keys, because the internal representation is typically a dictionary, which cannot have duplicate keys. We'd need to write our own data structure. However, this issue is very unlikely, and generally JSON with duplicate keys is discouraged (e.g. [RFC 7493](https://datatracker.ietf.org/doc/html/rfc7493#section-2.3)). So, I'll mark this as wontfix.
